branch-defaults:
  master:
    environment: Onebharat-foreigntent-env
environment-defaults:
  Onebharat-foreigntent-env:
    branch: null
    repository: null
global:
  application_name: onebharat-foreigntent
  default_ec2_keyname: null
  default_platform: Go 1 running on 64bit Amazon Linux 2023
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
